name: test_php
on: push

jobs:
  test_php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, pcov
          tools: cs2pr

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Show PHP Versions
        run: |
          php -v
      - name: Show PHP Extensions
        run: |
          php -m

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore composer cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Run composer install
        run: |
          composer install -n

      - name: Run php-cs-fixer
        run: |
          vendor/bin/php-cs-fixer fix \
            --dry-run \
            -vvv \
            --config=.php_cs.dist \
            --format=checkstyle | cs2pr

      - name: Run phpstan
        run: |
          vendor/bin/phpstan analyse \
            --memory-limit=-1 \
            --error-format=github

      - name: Run psalm
        run: |
          vendor/bin/psalm \
            --memory-limit=-1 \
            --output-format=github

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit
